name: ADGC
models:
  ADGC:
    layout: |
      xxxxxxxxx
      AAAADDDDx
      AAAADDDDx
      AAAADDDDx
      AAAADDDDx
      GGGGCCCCx
      GGGGCCCCx
      GGGGCCCCx
      GGGGCCCCx
  FILES:
    layout: |
      xxxxxxxxx
      AAAABBBBx
      AAAABBBBx
      CCCCDDDDx
      EEEEFFFFx
      HHHHZZZZx
      HHHHZZZZx
      HHHHZZZZx
      HHHHZZZZx

scales:
  C_major: [C, D, E, F, G, A, B]
colors:
  C: [255, 0, 0]
  D: [0, 255, 0]
  E: [0, 0, 255]
  F: [255, 255, 0]
  G: [0, 255, 255]
  A: [255, 0, 255]
  B: [128, 128, 128]
file_char_and_locations:
  Z: "./sounds/upla.wav"
  Y: "./sounds/beezoo.wav"
  H: "./sounds/beezoo.wav"
  U: "./sounds/upla.wav"
file_colors:
  Z: [128, 0, 0]
  Y: [0, 128, 0]
  H: [0, 0, 128]
  U: [128, 128, 0]
debounce: true  # Add this setting to enable/disable debouncing
